#!/bin/sh
echo Installing buck dependencies

sudo apt-get install default-jre
sudo apt-get install openjdk-7-jdk
sudo apt-get install ant

echo downloading bucl

git clone https://github.com/facebook/buck.git  
cd buck  

echo building buck

ant  
./bin/buck --help

echo Adding buck to the path
PATH=`pwd`/bin:$PATH
export PATH
cd ..

echo Checking buck is there
which buck



